version: '3.8'

services:
  app:
    build: ..
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=app_user
      - DB_PASSWORD=secure_password
      - DB_NAME=delivery_app
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: delivery_app
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: