version: '3.8'

services:
  app:
    build: .
    container_name: delivery-app
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=docker
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=app_user
      - DB_PASSWORD=secure_password
      - DB_NAME=delivery_app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - delivery-network

  db:
    image: postgres:15-alpine
    container_name: delivery-db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: delivery_app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d delivery_app"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - delivery-network

volumes:
  pgdata:

networks:
  delivery-network:
    driver: bridge